// --- BASE DE DATOS JSON DE PRODUCTOS LIMPIOS (SIN TACHADOS) ---
const productosData = [
            // PARA ALGODÓN - REACTIVOS BIFUNCIONALES
            { name: "Amarillo Reactivo 160", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Amarillo Reactivo 145", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Naranja Reactivo 122", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Rojo Reactivo 195", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Rojo Reactivo NS H/C", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Azul Reactivo 21", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Azul Reactivo 19", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Azul Reactivo 222", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Negro Reactivo 5", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Negro Reactivo HFGR", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Negro Reactivo RGB", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },
            { name: "Negro Reactivo Intenso NS", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Bifuncionales" },

            // PARA ALGODÓN - MONOCLOROTRIAZINA (HE)
            { name: "Amarillo Reactivo 84", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Monoclorotriazina (HE)" },
            { name: "Naranja Reactivo 84", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Monoclorotriazina (HE)" },
            { name: "Rojo Reactivo 120", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Monoclorotriazina (HE)" },
            { name: "Rojo Reactivo 141", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Monoclorotriazina (HE)" },
            { name: "Azul Reactivo 71", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Monoclorotriazina (HE)" },
            { name: "Azul Reactivo 198", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Monoclorotriazina (HE)" },
            { name: "Azul Reactivo 171", category: "algodon", classKey: "algodon", subcategory: "Colorantes Reactivos - Monoclorotriazina (HE)" },

            // PARA ALGODÓN - COLORANTES DIRECTOS
            { name: "Amarillo Directo Fluo F8G", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Amarillo Directo 44", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Amarillo Directo 50", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Naranja Directo 26", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Rosa Directo 227", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Rojo Directo 81", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Rojo Directo 23", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Rojo Directo 243", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Café Directo 95", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Café Directo 2", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Verde Directo 1", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Violeta Directo 51", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Azul Directo 86", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Azul Directo 199", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Azul Directo NSG", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Azul Rey Directo NS", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Azul Directo 15", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Azul Directo 80", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Azul Directo 201", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Azul Directo 2", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Azul Directo 151", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Azul Directo 200", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Negro Directo 22", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },
            { name: "Negro Directo 38", category: "algodon", classKey: "algodon", subcategory: "Colorantes Directos" },

            // COLORANTES AL AZUFRE
            { name: "Negro al Azufre", category: "algodon", classKey: "algodon", subcategory: "Colorantes al Azufre" },

            // PARA POLIÉSTER - DISPERSOS
            { name: "Amarillo Disperso Fluo 82", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Amarillo Disperso Fluo 10 G", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Naranja Disperso Fluo", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Rojo Disperso 277", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Rojo Disperso 362", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Violeta Disperso CN", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Amarillo Disperso 114", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Amarillo Disperso 211", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Amarillo Disperso 54", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Naranja Disperso 25", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Naranja Disperso 30", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Magenta Disperso NS", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Rojo Disperso 60", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Rojo Disperso 1", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Rojo Disperso 343", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Rojo Disperso 167", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Rojo Disperso 73", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Violeta Disperso SR", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Azul Disperso 60", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Azul Disperso 354", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Azul Disperso 56", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Azul Disperso 183", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Azul Disperso 366", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Azul Disperso 79", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Azul Disperso EXSF", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Negro Disperso EXSF", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Negro Disperso CC3R", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },
            { name: "Negro Disperso NSPG", category: "poliester", classKey: "poliester", subcategory: "Colorantes Dispersos" },

            // PARA POLIÉSTER - TRANSFER
            { name: "Amarillo Transfer NS Fluo", category: "poliester", classKey: "poliester", subcategory: "Colorantes para Transfer" },
            { name: "Rosa Transfer NS Fluo", category: "poliester", classKey: "poliester", subcategory: "Colorantes para Transfer" },
            { name: "Amarillo Transfer 4G", category: "poliester", classKey: "poliester", subcategory: "Colorantes para Transfer" },
            { name: "Naranja Transfer 2BP", category: "poliester", classKey: "poliester", subcategory: "Colorantes para Transfer" },
            { name: "Escarlata Transfer EMV", category: "poliester", classKey: "poliester", subcategory: "Colorantes para Transfer" },
            { name: "Rojo Transfer 2BP", category: "poliester", classKey: "poliester", subcategory: "Colorantes para Transfer" },
            { name: "Azul Rey Transfer FBLN", category: "poliester", classKey: "poliester", subcategory: "Colorantes para Transfer" },
            { name: "Turquesa Transfer BP", category: "poliester", classKey: "poliester", subcategory: "Colorantes para Transfer" },
            { name: "Negro Transfer NST", category: "poliester", classKey: "poliester", subcategory: "Colorantes para Transfer" },

            // COLORANTES ÁCIDOS
            { name: "Amarillo Ácido 49", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Amarillo Ácido 219", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Naranja Ácido 67", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Naranja Ácido 156", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Rojo Ácido 52", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Rojo Ácido NG", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Rojo Ácido 151", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Rojo Ácido 114", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Rojo Ácido 131", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Rojo Ácido 249", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Rojo Ácido 337", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Rojo Ácido 299", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Azul Ácido 185", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Azul Ácido 324", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Azul Ácido 62", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Azul Ácido 113", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },
            { name: "Negro Ácido 194", category: "acidos", classKey: "acidos", subcategory: "Colorantes Ácidos" },

            // COLORANTES SOLVENTES
            { name: "Amarillo Solvente Fluo 3G", category: "solventes", classKey: "solventes", subcategory: "Colorantes Solventes" },
            { name: "Amarillo Solvente 16", category: "solventes", classKey: "solventes", subcategory: "Colorantes Solventes" },
            { name: "Amarillo Solvente 163", category: "solventes", classKey: "solventes", subcategory: "Colorantes Solventes" },
            { name: "Rojo Solvente 24", category: "solventes", classKey: "solventes", subcategory: "Colorantes Solventes" },
            { name: "Rojo Solvente 195", category: "solventes", classKey: "solventes", subcategory: "Colorantes Solventes" },
            { name: "Azul Solvente 36", category: "solventes", classKey: "solventes", subcategory: "Colorantes Solventes" },
            { name: "Azul Solvente 97", category: "solventes", classKey: "solventes", subcategory: "Colorantes Solventes" },
            { name: "Rojo a la Cuba 41", category: "solventes", classKey: "solventes", subcategory: "Otros Colorantes" },

            // PIGMENTOS
            { name: "Amarillo Pigmento Fluo", category: "pigmentos", classKey: "pigmentos", subcategory: "Pigmentos" },
            { name: "Salmón Pigmento Fluo", category: "pigmentos", classKey: "pigmentos", subcategory: "Pigmentos" },
            { name: "Coral Pigmento Fluo", category: "pigmentos", classKey: "pigmentos", subcategory: "Pigmentos" },
            { name: "Rosa Pigmento Fluo", category: "pigmentos", classKey: "pigmentos", subcategory: "Pigmentos" },
            { name: "Limón Pigmento Fluo", category: "pigmentos", classKey: "pigmentos", subcategory: "Pigmentos" },

            // GLITTERS
            { name: "Glitter Multicolor", category: "glitters", classKey: "glitters", subcategory: "Glitters" },
            { name: "Glitter Plata", category: "glitters", classKey: "glitters", subcategory: "Glitters" },
            { name: "Glitter Dorado", category: "glitters", classKey: "glitters", subcategory: "Glitters" },
            { name: "Glitter Rosa", category: "glitters", classKey: "glitters", subcategory: "Glitters" },

            // PRODUCTOS AUXILIARES
            { name: "Alfamilaza", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Enzimas" },
            { name: "Enzima Ácida", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Enzimas" },
            { name: "Enzima Neutra", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Enzimas" },
            { name: "Detergente Neutro", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Detergentes" },
            { name: "Detergente Alcalino", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Detergentes" },
            { name: "Betes Clean", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Detergentes" },
            { name: "Humectante", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Humectantes" },
            { name: "Fijador", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Fijadores" },
            { name: "Base Bloqueador Poliéster", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Bloqueadores" },
            { name: "Dispersante para Nylon", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Dispersantes" },
            { name: "Dispersante", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Dispersantes" },
            { name: "Disp. p/ algodón (Anotación)", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Dispersantes" },
            { name: "Base Suavizante Miel", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Suavizantes" },
            { name: "Suavizante para Nylon", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Suavizantes" },
            { name: "Silicon", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Suavizantes" },
            { name: "Bínder", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Otros" },
            { name: "Secuestrante", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Otros" },
            { name: "Antiespumante (Anotación)", category: "auxiliares", classKey: "auxiliares", subcategory: "Auxiliares - Otros" },

            // BLANCOS ÓPTICOS
            { name: "White BYX H/C", category: "blancos", classKey: "blancos", subcategory: "Blancos Ópticos - Para Algodón" },
            { name: "Óptico Stone 2B", category: "blancos", classKey: "blancos", subcategory: "Blancos Ópticos - Para Algodón" },
            { name: "Óptico Abrillantador 2B", category: "blancos", classKey: "blancos", subcategory: "Blancos Ópticos - Para Algodón" },
            { name: "White Cotton NS", category: "blancos", classKey: "blancos", subcategory: "Blancos Ópticos - Para Algodón" },
            { name: "White BYX NYL H/C", category: "blancos", classKey: "blancos", subcategory: "Blancos Ópticos - Para Nylon" },
            { name: "Abrillantador PET NSN", category: "blancos", classKey: "blancos", subcategory: "Blancos Ópticos - Para Poliéster" },
            { name: "Abrillantador PET NSB", category: "blancos", classKey: "blancos", subcategory: "Blancos Ópticos - Para Poliéster" },
            { name: "White OB-1", category: "blancos", classKey: "blancos", subcategory: "Blancos Ópticos - Para Plástico" }
        ];

